SET(LEDGER_INCLUDE_DIRS "")
SET(LEDGER_LINKER_LIBS "")
SET(LEDGER_DEFINITIONS "")

FIND_PACKAGE(Protobuf REQUIRED)

FIND_PACKAGE(LibEvent REQUIRED)
LIST(APPEND DIST_INCLUDE_DIRS ${LIBEVENT_INCLUDE_DIRS})
LIST(APPEND DIST_LINKER_LIBS ${LIBEVENT_LIBRARIES})

FIND_PACKAGE(Boost REQUIRED COMPONENTS ${BOOST_COMPONENT})
IF(Boost_FOUND)
    LIST(APPEND LEDGER_INCLUDE_DIRS ${Boost_INCLUDE_DIRS})
    LIST(APPEND LEDGER_LINKER_LIBS ${Boost_LIBRARIES})
ENDIF()

FIND_PACKAGE(Rocksdb REQUIRED)
IF(ROCKSDB_FOUND)
  LIST(APPEND LEDGER_INCLUDE_DIRS ${ROCKSDB_INCLUDES})
  LIST(APPEND LEDGER_LINKER_LIBS ${ROCKSDB_LIBRARIES})
  ADD_DEFINITIONS(-DUSE_ROCKSDB)
ENDIF()

FIND_PACKAGE(CryptoPP REQUIRED)
IF(CRYPTOPP_FOUND)
  LIST(APPEND LEDGER_INCLUDE_DIRS ${CRYPTOPP_INCLUDE_DIR})
  LIST(APPEND LEDGER_LINKER_LIBS ${CRYPTOPP_LIBRARIES})
ENDIF()

INCLUDE_DIRECTORIES(SYSTEM ${LEDGER_INCLUDE_DIRS})
# MESSAGE(STATUS "INCLUDE ${LEDGER_INCLUDE_DIRS}")
